# Generated by Django 2.2.2 on 2019-08-07 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='发布会标题')),
                ('limit', models.IntegerField(verbose_name='参加人数')),
                ('status', models.BooleanField(verbose_name='状态')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('start_time', models.DateTimeField(verbose_name='发布会时间')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '发布会表',
                'verbose_name_plural': '发布会表',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=64, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('sign', models.BooleanField(verbose_name='签到状态')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.Event', verbose_name='发布会')),
            ],
            options={
                'unique_together': {('event', 'phone')},
            },
        ),
    ]
