# Generated by Django 2.2.2 on 2019-08-07 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': '嘉宾表', 'verbose_name_plural': '嘉宾表'},
        ),
    ]
